name: Data Update

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  data_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull & update submodules
        run: |
          git submodule update --init
          git submodule update --remote
          
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: |
          npm ci
          npm start
          npm run deploy
  
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Data Update"
